### PR TITLE
(wip) Restyle/send card

### LINKED ISSUE #347: "What's this?" link inside gas customization needs to do something
Inside gas customization:
image

### LINKED ISSUE #353: Firefox gas customization looks like crap
image

### PR DESCRIPTION
**Pull request by as-dr**
# Changes
1. Moved `Customize` tx below "Transaction Fee"
1. Updated structure, postioning of the Customize copy and unicode arrow
1. Updated structure and positioning of the denominations
1. Gave the `Numbers` input component a `fontSize` prop that we can pass down from the `Funds` input component in order to customize the fontSize of those inputs in that component (before, the declarations were overriden by the defaults in the base `Numbers` input component.
1. Increased spacing of Total section to improve legibility, information hierarchy.
1. Added new "medium" variant to "Num" text style and updated Num font from Atlas Medium to Grotesk.

image

image

This also incidentally (though intentionally) updates `BalanceCard` to use Atlas Grotesk over Medium:

image

### CODE REVIEW

**Comment by Schwartz10** [comment]
@as-dr should we follow the same background-color styling patterns for the inputs?

Also, looks like the left border on the address input disappeared too. I have an incoming PR that will catch those CSS changes in the snapshots, so this won't happen again unnoticed in code.

image

**Comment by as-dr** [comment]
Latest

Screen Shot 2020-04-10 at 4 58 15 PM

**Review by Schwartz10 — CHANGES_REQUESTED** [review]
Check firefox @as-dr 

image

**Comment by Schwartz10** [comment]
@as-dr i also see some weird behavior when opening the gas customization screen and changing screen widths, see these screenshots:

normal:

image

Smaller widths, right borders disappear:

image

Open gas customization, borders go nuts:

image

**Comment by as-dr** [comment]
Weird, the gasCustomization border issues didn't appear for me previously but I know why they're being caused. Will fix that first then move to resolve Firefox compatibility.

**Comment by as-dr** [comment]
Should be good:

image

**Pull request merged**
