### PR TITLE
Feat/investor saft support

### PR DESCRIPTION
**Pull request by Schwartz10**
Hey @as-dr i think this is pretty close to ready for your review. 

image
image
image
image
image
image

I still need to implement validation for the investor UUIDs. But i can get to that in parallel

### CODE REVIEW

**Comment by as-dr** [comment]
@Schwartz10 

**Account Switcher Title**

1. Should we change "Switch Accounts" to "Select Account"?

----

**Final Step, Proposed Changes**


1. The final step, "Send Email" may be a little confusing, because it implies (from the user's perspective) that *they* need to send an email. 

1. An alternative title might be "Confirm ID & Address"
1. An alternative copy might be "Once confirmed, we'll generate an email with your investor ID and associated Filecoin address to send to Protocol Labs".
1. An alternative Primary Button copy might be "Generate Email" 

I'm assuming this opens their default email client with all of these details included within it?

**Comment by Schwartz10** [comment]
Just made all your suggested changes. And yeah, it opens their default (native) email client with the details in it.

Will add tests and then merge once ready

**Comment by Schwartz10** [comment]
This is ready to be merged, tests can be added once ian updates the pre mainnet launch spec. None of the investor pages will show in prod yet

**Comment by Schwartz10** [comment]
This is ready to be merged, tests can be added once ian updates the pre mainnet launch spec. None of the investor pages will show in prod yet

**Pull request merged**
