### PR TITLE
Add snapshot tests for shared components

### PR DESCRIPTION
**Pull request by listenaddress**

### CODE REVIEW

**Comment by Schwartz10** [comment]
@listenaddress is this ready for review?

**Comment by listenaddress** [comment]
Few more to add. Will get to it today or tomorrow.

**Comment by Schwartz10** [comment]
Hey @listenaddress can you just do whatever cleanup you need to do on this PR before adding more tests to other shared components so we can get this in? We should try to get tests in as fast as we can so that while alex and i are making changes, we’re seeing what things are breaking. 

A couple things i noticed on first review, which im sure you were planning on getting to as a cleanup:

- commented out copy to clipboard test. Look at jest.spyOn to mock the `copytoclipboard`
- test descriptions have copied text from previous tests
- AccountCard should take a snapshot of a non ledger wallet too (just render one with a different wallet type, should take 1 sec)
- button tests - add a test to make sure the button calls the `onClick` function when clicked

besides those few things this looks good.

**Comment by listenaddress** [comment]
This will fail now, but once this is merged —> https://github.com/openworklabs/filecoin-web-wallet/pull/387, it should work.

**Comment by listenaddress** [comment]
Otherwise it's cleaned up and ready to go.

**Pull request merged**
